version: "3.9"

services:
  broker:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  publisher:
    build: ./pub
    container_name: mqtt-publisher
    environment:
      - OBU_ID=1
      - MQTT_BROKER=mqtt-broker
      - MQTT_PORT=1883
      - DATA_TYPE=BPR
      - QOS_LEVEL=0
      - DURATION=300
    depends_on:
      - broker

  subscriber:
    build: ./sub
    container_name: mqtt-subscriber
    environment:
      - MQTT_BROKER=mqtt-broker
      - MQTT_PORT=1883
      - DATA_TYPE=BPR
      - QOS_LEVEL=0
      - BANDWIDTH=128
    volumes:
      - ./data:/data
    depends_on:
      - broker
